## Problem 2: VaR and ES

In [15]:
import numpy as np
from scipy.stats import norm

In [12]:
mu = np.zeros(3)
mu= mu.T
print(mu)

[0. 0. 0.]


In [13]:
sigma = 0.01*np.array([30, 20, 15])
sigma=sigma.T
print(sigma)

[0.3  0.2  0.15]


In [22]:
R= np.array([[1,0.8, 0.5],[0.8,1,0.3],[0.5,0.3,1]])
print(R)

[[1.  0.8 0.5]
 [0.8 1.  0.3]
 [0.5 0.3 1. ]]


In [23]:
Sigma_n = np.outer(sigma, sigma) * R
print(Sigma_n)

[[0.09   0.048  0.0225]
 [0.048  0.04   0.009 ]
 [0.0225 0.009  0.0225]]


In [14]:
w = 0.01*np.array([50, 20, 30])
w = w.T
print(w)

[0.5 0.2 0.3]


Here the equations will be displayed

In [21]:
a= 0.99
z_a = -norm.ppf(a)
print(z_a)

-2.3263478740408408


In [45]:
import math as mt

VaRsens_w1= round(mu[0] + z_a * (Sigma_n@w)[0] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
VaRsens_w2= round(mu[1] + z_a * (Sigma_n@w)[1] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
VaRsens_w3= round(mu[2] + z_a * (Sigma_n@w)[2] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)

ESsens_w1= round(mu[0] - (norm.pdf(z_a)/(1-a)) * (Sigma_n@w)[0] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
ESsens_w2= round(mu[1] - (norm.pdf(z_a)/(1-a)) * (Sigma_n@w)[1] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
ESsens_w3= round(mu[2] - (norm.pdf(z_a)/(1-a)) * (Sigma_n@w)[2] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)


print(VaRsens_w1)
print(VaRsens_w2)
print(VaRsens_w3)

print('\n')

print(ESsens_w1)
print(ESsens_w2)
print(ESsens_w3)



-0.6839
-0.3868
-0.2207


-0.7835
-0.4431
-0.2529
