In [1]:
import numpy as np
from numpy import linalg as LA

# Solution
As we refview on class with Dr Sebastien, the $\mu$ vector is:

In [2]:
mu = 0.01*np.array([2, 7, 15, 20])
mu= mu.T
print(mu)

[0.02 0.07 0.15 0.2 ]


On the other hand, $\sigma$ is:

In [3]:
sigma = 0.01*np.array([5, 12, 17, 25])
sigma=sigma.T
print(sigma)

[0.05 0.12 0.17 0.25]


Finally, the correlation matrix

In [10]:
R= np.array([[1,0.3, 0.3,0.3],[0.3,1,0.6,0.6],[0.3,0.6,1,0.6],[0.3,0.6,0.6,1]])
print(R)

[[1.  0.3 0.3 0.3]
 [0.3 1.  0.6 0.6]
 [0.3 0.6 1.  0.6]
 [0.3 0.6 0.6 1. ]]


In [11]:
Sigma_n = np.outer(sigma, sigma) * R
print(Sigma_n)

[[0.0025  0.0018  0.00255 0.00375]
 [0.0018  0.0144  0.01224 0.018  ]
 [0.00255 0.01224 0.0289  0.0255 ]
 [0.00375 0.018   0.0255  0.0625 ]]


Now is time to get the intermediate values "A", "B" and "C"

In [12]:
n= len(mu)

ones_n = np.ones(n)

A= ones_n @ LA.inv(Sigma_n) @ ones_n.T
B= mu @ LA.inv(Sigma_n) @ ones_n.T
C= mu @ LA.inv(Sigma_n) @ mu.T

print(A)
print(B)
print(C)

423.6149806869816
6.807020715428303
0.9065089304034119


Now, the lagrange multipliers:

In [15]:
m= 0.045 # The return expected in out portffolio

Denom= A*C-B**2

lambda_Lagr = (A*m-B)/ Denom

gamma_Lagr = (C-B*m)/ Denom

print(lambda_Lagr)
print(gamma_Lagr)

0.036294202989022174
0.0017774267736771414


Lastly, the optimat asset allocation w:

In [16]:
weights =  LA.inv(Sigma_n) @ (lambda_Lagr*mu+gamma_Lagr*ones_n)

print(weights)


[0.78511066 0.05386419 0.13355472 0.02747042]


Verifying the constraints:

In [17]:

print(round(mu@weights.T,4))

print(round(sum(weights),4))



0.045
1.0


## Problem 2: VaR and ES

In [15]:
import numpy as np
from scipy.stats import norm

In [12]:
mu = np.zeros(3)
mu= mu.T
print(mu)

[0. 0. 0.]


In [13]:
sigma = 0.01*np.array([30, 20, 15])
sigma=sigma.T
print(sigma)

[0.3  0.2  0.15]


In [22]:
R= np.array([[1,0.8, 0.5],[0.8,1,0.3],[0.5,0.3,1]])
print(R)

[[1.  0.8 0.5]
 [0.8 1.  0.3]
 [0.5 0.3 1. ]]


In [23]:
Sigma_n = np.outer(sigma, sigma) * R
print(Sigma_n)

[[0.09   0.048  0.0225]
 [0.048  0.04   0.009 ]
 [0.0225 0.009  0.0225]]


In [14]:
w = 0.01*np.array([50, 20, 30])
w = w.T
print(w)

[0.5 0.2 0.3]


Here the equations will be displayed

In [21]:
a= 0.99
z_a = -norm.ppf(a)
print(z_a)

-2.3263478740408408


In [45]:
import math as mt

VaRsens_w1= round(mu[0] + z_a * (Sigma_n@w)[0] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
VaRsens_w2= round(mu[1] + z_a * (Sigma_n@w)[1] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
VaRsens_w3= round(mu[2] + z_a * (Sigma_n@w)[2] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)

ESsens_w1= round(mu[0] - (norm.pdf(z_a)/(1-a)) * (Sigma_n@w)[0] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
ESsens_w2= round(mu[1] - (norm.pdf(z_a)/(1-a)) * (Sigma_n@w)[1] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)
ESsens_w3= round(mu[2] - (norm.pdf(z_a)/(1-a)) * (Sigma_n@w)[2] * (1/mt.sqrt(w @ Sigma_n @ w.T)),4)


print(VaRsens_w1)
print(VaRsens_w2)
print(VaRsens_w3)

print('\n')

print(ESsens_w1)
print(ESsens_w2)
print(ESsens_w3)



-0.6839
-0.3868
-0.2207


-0.7835
-0.4431
-0.2529
