In [1]:
range(10)

range(0, 10)

In [2]:
a=range(5,10)

In [5]:
print(a)

range(5, 10)


In [6]:
a

range(5, 10)

In [7]:
x= range(0,101,10)

In [8]:
x

range(0, 101, 10)

In [10]:
x[5]

50

In [12]:
for i in range(0, 11):
   print(x[i])


0
10
20
30
40
50
60
70
80
90
100


In [14]:
import cmath as cm

y=cm.sqrt(-4)

print(y)

2j


# Numpy

In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
import numpy.random as npr

In [3]:
data =[1,2,3,4,5]

arr1=np.array(data)

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
print(type(data))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
arr1.ndim

1

In [11]:
A=np.array([[1,2],[3,4]])
A.ndim

2

In [12]:
b=np.array([[1],[2]])

np.dot(A,b)

array([[ 5],
       [11]])

In [13]:
X=np.zeros(3)
print(X)

[0. 0. 0.]


In [15]:
X1=np.zeros((3,3))
print(X1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
Z=np.ones((3,2))
print(Z)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
k= np.arange(15)
print(k[1])

1


In [24]:
k2= np.arange(50,110,10)
for i in range(0,6):    
    print(k2[i])
    
    

50
60
70
80
90
100


In [25]:
k2.reshape(2,3)

array([[ 50,  60,  70],
       [ 80,  90, 100]])

In [26]:
arr2=np.empty((10,4))
print(arr2)

[[3.62651200e-317 1.16270834e-311 2.18829737e-312 0.00000000e+000]
 [1.69484279e-319 2.18829737e-312 0.00000000e+000 1.16271090e-311]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 1.16272263e-311]
 [0.00000000e+000 4.94065646e-324 6.95236682e-310 2.02369289e-320]
 [4.94065646e-324 6.95236707e-310 9.88131292e-324 6.95236682e-310]
 [6.95236682e-310 7.71229359e-317 0.00000000e+000             nan]
 [0.00000000e+000 0.00000000e+000 3.56043053e-307 1.60219306e-306]
 [7.56571288e-307 7.56587584e-307 1.37961302e-306 1.05699242e-307]
 [8.01097889e-307 2.22522868e-306 1.33511562e-306 1.24611402e-306]
 [1.24611538e-306 2.13623116e-306 8.34423917e-308 2.29179042e-312]]


In [27]:
arr2=np.empty((10,4))
for i in range(10):
    arr2[i]=i-1
    
print(arr2)    

[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]
 [ 8.  8.  8.  8.]]


In [28]:
I=np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
arr3=np.arange(20)
x=npr.shuffle(arr3)
print(arr3)

[ 7  4  1  5 10 11 17  9 18 14  3  8  0 12 15  6 16 19  2 13]
None


In [31]:
arr3

array([ 7,  4,  1,  5, 10, 11, 17,  9, 18, 14,  3,  8,  0, 12, 15,  6, 16,
       19,  2, 13])