In [32]:
range(10)

range(0, 10)

In [33]:
a=range(5,10)

In [34]:
print(a)

range(5, 10)


In [35]:
a

range(5, 10)

In [36]:
x= range(0,101,10)

In [37]:
x

range(0, 101, 10)

In [38]:
x[5]

50

In [39]:
for i in range(0, 11):
   print(x[i])


0
10
20
30
40
50
60
70
80
90
100


In [40]:
import cmath as cm

y=cm.sqrt(-4)

print(y)

2j


# Numpy

In [41]:
import numpy as np
import numpy.linalg as LA

In [42]:
import numpy.random as npr

In [43]:
data =[1,2,3,4,5]

arr1=np.array(data)

In [44]:
arr1

array([1, 2, 3, 4, 5])

In [45]:
print(type(data))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [46]:
arr1.ndim

1

In [47]:
A=np.array([[1,2],[3,4]])
A.ndim

2

In [48]:
b=np.array([[1],[2]])

np.dot(A,b)

array([[ 5],
       [11]])

In [49]:
X=np.zeros(3)
print(X)

[0. 0. 0.]


In [50]:
X1=np.zeros((3,3))
print(X1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
Z=np.ones((3,2))
print(Z)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [52]:
k= np.arange(15)
print(k[1])

1


In [53]:
k2= np.arange(50,110,10)
for i in range(0,6):    
    print(k2[i])
    
    

50
60
70
80
90
100


In [54]:
k2.reshape(2,3)

array([[ 50,  60,  70],
       [ 80,  90, 100]])

In [55]:
arr2=np.empty((10,4))
print(arr2)

[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]
 [ 8.  8.  8.  8.]]


In [56]:
arr2=np.empty((10,4))
for i in range(10):
    arr2[i]=i-1
    
print(arr2)    

[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]
 [ 8.  8.  8.  8.]]


In [57]:
I=np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [58]:
arr3=np.arange(20)
x=npr.shuffle(arr3)
print(arr3)

[16 15  7  3  6 14 18  2 13  8  1  0  5 19 10 17 12 11  4  9]


In [59]:
arr3

array([16, 15,  7,  3,  6, 14, 18,  2, 13,  8,  1,  0,  5, 19, 10, 17, 12,
       11,  4,  9])

In [88]:
matrix_singlrow=arr2.reshape(40,1)
print(type(matrix_singlrow))
print(matrix_singlrow.ndim)
print(matrix_singlrow)

<class 'numpy.ndarray'>
2
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 6.]
 [ 6.]
 [ 6.]
 [ 6.]
 [ 7.]
 [ 7.]
 [ 7.]
 [ 7.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]]


In [94]:

matrix_singlrow2=[]

for i in range(10):
    for j in range(4):
        matrix_singlrow2.append(arr2[i,j])

        
#print(matrix_singlrow2)

m2=np.array(matrix_singlrow2)
print(type(m2))
print(m2.ndim)
print(m2.T)

<class 'numpy.ndarray'>
1
[-1. -1. -1. -1.  0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.
  3.  3.  4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  7.  7.  7.  7.
  8.  8.  8.  8.]


In [132]:
print(np.hstack([m2]).T)

print(np.vstack([m2]).T)

[-1. -1. -1. -1.  0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.
  3.  3.  4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  7.  7.  7.  7.
  8.  8.  8.  8.]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 6.]
 [ 6.]
 [ 6.]
 [ 6.]
 [ 7.]
 [ 7.]
 [ 7.]
 [ 7.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]]


In [96]:
from numpy import linalg as LA
A=np.array([[1,2],[3,4]])

LA.matrix_power(A,2)

array([[ 7, 10],
       [15, 22]])

In [100]:
B=np.array([[1,0],[0,1]])
B

array([[1, 0],
       [0, 1]])

In [103]:
np.concatenate((A,B),axis=1)


array([[1, 2, 1, 0],
       [3, 4, 0, 1]])

In [105]:
x=np.array([1,2,3])
y=np.array([5,6,7])

np.concatenate([x,y])

array([1, 2, 3, 5, 6, 7])

In [109]:

np.concatenate([[x],[y]])

array([[1, 2, 3],
       [5, 6, 7]])

In [110]:
np.concatenate([[x.T],[y.T]])

array([[1, 2, 3],
       [5, 6, 7]])

In [114]:
np.concatenate([[x.T],[y.T]]).T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [115]:
np.concatenate([[x],[y]]).T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [122]:
np.vstack([x,y])


array([[1, 2, 3],
       [5, 6, 7]])

In [124]:
np.vstack([[x],[y]]).T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [125]:
np.hstack([[x],[y]])

array([[1, 2, 3, 5, 6, 7]])

In [135]:
w=np.concatenate([x,y])
x1,x2,x3=np.split(w,3)
print(x1)
print(x2)
print(x3)

[1 2]
[3 5]
[6 7]


In [136]:
w2=np.concatenate([x,y])
x1,x2,x3=np.hsplit(w,3)
print(x1)
print(x2)
print(x3)

[1 2]
[3 5]
[6 7]


In [146]:
arr= np.arange(20).reshape((5,4))

print(arr)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [152]:
upper,lower= np.vsplit(arr,[7])
print(upper)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [148]:
left, right=np.hsplit(arr,2)

In [149]:
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]


In [150]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


# Solve Linear Systems

In [156]:
A=np.array([[2,1,-2],[3,2,2],[5,4,3]])

b=np.array([10,1,4])

x=LA.solve(A,b)

x

array([ 1.,  2., -3.])

# Eigenvalues

In [157]:
eigval,eigvec=LA.eig(A)

eigval

eigvec


array([[ 0.26214869-0.31993814j,  0.26214869+0.31993814j,
         0.52072636+0.j        ],
       [-0.46391997-0.00306921j, -0.46391997+0.00306921j,
        -0.82782708+0.j        ],
       [-0.78338145+0.j        , -0.78338145-0.j        ,
         0.20867771+0.j        ]])